spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:18346/railway
#    url: jdbc:postgresql://localhost:5433/employee_training
    username: postgres
    password: bABffga1BDBD5-Af55ae2a621-cBA134
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #    show-sql: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  # email
  mail:
    host: smtp.gmail.com
    port: 587
    username: sample@mail.com
    password: password
    sender:
      name: admin
      email: no-reply@test.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  packages-to-scan: com.rifqimuhammadaziz.employeetraining.controller
  swagger-ui:
    path: /
    disable-swagger-default-url: true

security:
  jwt:
    enabled: true
    secret_key: s3cr3t
  bcrypt:
    cost: 13

app:
  uploadto:
    cdn: "./cdn/"

BASE_URL: http://localhost:8080

cron:
  expression: '0 0 0 */14 * *'